const playerStartingDeck = [
  {
    cardId: 1,
    amount: 3,
    attributes: [],
  },
  {
    cardId: 2,
    amount: 7,
  },
];

const basicCards = [
  {
    cardId: 1,
    name: "Dagger",
    attributes: [],
    icons: {
      cost: 0,
      attack: 1,
      coin: 0,
    },
    text: "",
    abilities: [],
  },
  {
    cardId: 2,
    name: "Copper",
    attributes: [],
    icons: {
      cost: 0,
      attack: 0,
      coin: 1,
    },
    text: "",
    abilities: [],
  },
  {
    cardId: 3,
    name: "Short Sword",
    attributes: [],
    icons: {
      cost: 4,
      attack: 2,
      coin: 0,
    },
    text: "",
    abilities: [],
  },
  {
    cardId: 4,
    name: "Silver",
    attributes: [],
    icons: {
      cost: 3,
      attack: 0,
      coin: 2,
    },
    text: "",
    abilities: [],
  },
];

const shopDeck1 = [
  {
    cardId: 5,
    name: "Gold Dagger",
    attributes: [],
    icons: {
      cost: 2,
      attack: 1,
      coin: 1,
    },
    text: "",
    abilities: [],
    amount: 2,
  },
  {
    cardId: 6,
    name: "Kriss Dagger",
    attributes: [],
    icons: {
      cost: 2,
      attack: 1,
      coin: 0,
    },
    text: "Discard 1 random card: Draw 1 card. ",
    abilities: [{ function: "discardCard", arg: ["drawCard", "1"] }],
    amount: 2,
  },
  {
    cardId: 7,
    name: "Hand Axe",
    attributes: [],
    icons: {
      cost: 2,
      attack: 1,
      coin: 0,
    },
    text: "Discard 1 random card: +2 attack",
    abilities: [{ function: "discardCard", arg: ["addAttack", "2"] }],
    amount: 2,
  },
  {
    cardId: 8,
    name: "Swift Sword",
    attributes: [],
    icons: {
      cost: 3,
      attack: 1,
      coin: 0,
    },
    text: "Draw 1 card",
    abilities: [{ function: "drawCard", arg: "1" }],
    amount: 2,
  },
  {
    cardId: 9,
    name: "Leather Armor",
    attributes: ["armor"],
    icons: {
      cost: 3,
      attack: 0,
      coin: 1,
    },
    text: "Draw 1 card",
    abilities: [{ function: "drawCard", arg: "1" }],
    amount: 2,
  },
  {
    cardId: 10,
    name: "War Hammer",
    attributes: [],
    icons: {
      cost: 3,
      attack: 2,
      coin: 0,
    },
    text: "If armor in play area: +2 attack",
    abilities: [{ function: "checkForArmor", arg: ["addAttack", "2"] }],
    amount: 2,
  },
  {
    cardId: 11,
    name: "Crystal Sword",
    attributes: [],
    icons: {
      cost: 4,
      attack: 1,
      coin: 2,
    },
    text: "",
    abilities: [],
    amount: 1,
  },
  {
    cardId: 12,
    name: "Mail Armor",
    attributes: ["armor"],
    icons: {
      cost: 4,
      attack: 0,
      coin: 1,
    },
    text: "Draw 2 Cards",
    abilities: [{ function: "drawCard", arg: "2" }],
    amount: 1,
  },
  {
    cardId: 13,
    name: "Battle Axe",
    attributes: [],
    icons: {
      cost: 4,
      attack: 2,
      coin: 0,
    },
    text: "If armor in play area: +2 attack",
    abilities: [{ function: "discardCard", arg: ["addAttack", "2"] }],
    amount: 1,
  },
  {
    cardId: 14,
    name: "Longsword",
    attributes: [],
    icons: {
      cost: 4,
      attack: 3,
      coin: 0,
    },
    text: "",
    abilities: [],
    amount: 1,
  },
  {
    cardId: 15,
    name: "Battle Hammer",
    attributes: [],
    icons: {
      cost: 4,
      attack: 2,
      coin: 0,
    },
    text: "If armor in play area: +2 attack",
    abilities: [{ function: "checkForArmor", arg: ["addAttack", "2"] }],
    amount: 1,
  },
  {
    cardId: 16,
    name: "Gold",
    attributes: ["armor"],
    icons: {
      cost: 5,
      attack: 0,
      coin: 3,
    },
    text: "",
    abilities: [],
    amount: 1,
  },
  {
    cardId: 17,
    name: "Katana",
    attributes: [],
    icons: {
      cost: 5,
      attack: 2,
      coin: 1,
    },
    text: "Draw 1 Card",
    abilities: [{ function: "drawCard", arg: "1" }],
    amount: 1,
  },
  {
    cardId: 18,
    name: "Gold Sword",
    attributes: [],
    icons: {
      cost: 5,
      attack: 2,
      coin: 2,
    },
    text: "",
    abilities: [],
    amount: 1,
  },
  {
    cardId: 19,
    name: "Plate Armor",
    attributes: [],
    icons: {
      cost: 6,
      attack: 0,
      coin: 2,
    },
    text: "",
    abilities: [{ function: "drawCard", arg: "3" }],
    amount: 1,
  },
  {
    cardId: 20,
    name: "Zweihander",
    attributes: [],
    icons: {
      cost: 6,
      attack: 4,
      coin: 0,
    },
    text: "",
    abilities: [],
    amount: 1,
  },
  {
    cardId: 21,
    name: "War Maul",
    attributes: [],
    icons: {
      cost: 7,
      attack: 4,
      coin: 0,
    },
    text: "If armor in play area: +3 attack",
    abilities: [{ function: "checkForArmor", arg: ["addAttack", "3"] }],
    amount: 1,
  },
];

export default basicCards;
export { playerStartingDeck, shopDeck1 };
